-- MySQL Script generated by MySQL Workbench
-- Sun Jan 18 23:34:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `my_db` ;

-- -----------------------------------------------------
-- Table `my_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_db`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parents_1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_parents_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `my_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_db`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `price` DECIMAL(10,2) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_1_idx` (`category_id` ASC) VISIBLE,
  INDEX `idx_products_name` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_products_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `my_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_db`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_db`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  `order_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `idx_orders_order_date` (`order_date` ASC) VISIBLE,
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `my_db`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_db`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_db`.`order_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_2_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_order_product` (`order_id` ASC, `product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `my_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `my_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
